--require 'user/fern'
--require 'user/fern-preview'
--require 'user/fern-renderer-nerdfont'
require("user.telescope")
require("user.bufferline")
require("user.nvim-treesitter")
require("user.nvim-colorizer")
require("user.mason")
require("user.nvim-lspconfig")
require("user.nvim-cmp")
require("user.indent-blankline")
require("user.nvim-autopairs")
require("user.nvim-ts-autotag")
require("user.aerial")
require("user.dap")
require("user.nvim-tree_lua")
require("user.filetype_nvim")
require("user.nvim-web-devicons")
require("user.dapui")
require("user.nvim-dap-virtual-text")
require("user.which-key")
require("user.nvim-luasnip")
require("user.null-ls")
require("user.trouble")
require("user.feline")
require("user.auto-session")
require("user.gitsigns")
require("user.notify")
require("user.fidget")
require("user.todo-comments")
require("user.bqf")
require("user.toggleterm")
require("user.git-nvim")
