--require 'user-settings/fern'
--require 'user-settings/fern-preview'
--require 'user-settings/fern-renderer-nerdfont'
require("user-settings/telescope")
require("user-settings/bufferline")
require("user-settings/nvim-treesitter")
require("user-settings/nvim-colorizer")
require("user-settings/nvim-lsp-installer")
require("user-settings/nvim-lspconfig")
require("user-settings/nvim-cmp")
require("user-settings/indent-blankline")
require("user-settings/nvim-autopairs")
require("user-settings/nvim-ts-autotag")
require("user-settings/aerial")
require("user-settings/dap")
require("user-settings/nvim-tree_lua")
require("user-settings/filetype_nvim")
require("user-settings/nvim-web-devicons")
require("user-settings/dapui")
require("user-settings/nvim-dap-virtual-text")
require("user-settings/which-key")
require("user-settings/nvim-luasnip")
require("user-settings/null-ls")
require("user-settings/trouble")
require("user-settings/feline")
require("user-settings/auto-session")
require("user-settings/gitsigns")
require("user-settings/notify")
require("user-settings/fidget")
