---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "css",
      "editorconfig",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "gpg",
      "graphql",
      "html",
      "javascript",
      "javascriptreact",
      "jsdoc",
      "json",
      "jsonc",
      "just",
      "kdl",
      "lua",
      "luadoc",
      "nix",
      "python",
      "query",
      "rust",
      "sql",
      "svelte",
      "tmux",
      "tsx",
      "typescript",
      "typespec",
      "vim",
      "vimdoc",
      "vue",
      "yaml",
    },
    highlight = {
      enable = true,
    },
  },
}
