[tools]
'npm:npm' = 'latest'
'npm:pnpm' = 'latest'

# Claude Code
# Ref: https://docs.anthropic.com/ja/docs/claude-code/overview
# Ref: https://spiess.dev/blog/how-i-use-claude-code
'npm:@anthropic-ai/claude-code' = 'latest'

# Gemini CLI
# https://github.com/google-gemini/gemini-cli
'npm:@google/gemini-cli' = 'latest'

# vtsls
# https://github.com/yioneko/vtsls
'npm:@vtsls/language-server' = 'latest'

# @vue/typescript-plugin
# https://www.npmjs.com/package/@vue/typescript-plugin
'npm:@vue/typescript-plugin' = 'latest'

# @vue/language-server
# https://www.npmjs.com/package/@vue/language-server
'npm:@vue/language-server' = 'latest'

# @astrojs/language-server
# https://github.com/withastro/language-tools
'npm:@astrojs/language-server' = 'latest'

# yaml-language-server
# https://github.com/redhat-developer/yaml-language-server
'npm:yaml-language-server' = 'latest'

'npm:typescript' = 'latest'

# Bun
bun = 'latest'

# Deno
deno = 'latest'

# Golang
go = 'latest'

# Node.js
node = ['lts', '23']

# Python
python = 'latest'

# Rust
rust = 'nightly'
'cargo:just-lsp' = 'latest'
'cargo:stylua' = 'latest'

# Taplo - TOML Toolkit
# https://github.com/tamasfe/taplo
'cargo:taplo-cli' = { version = 'latest', features = "lsp" }

[settings.npm]
bun = true
