[tools]
'npm:npm' = 'latest'
'npm:pnpm' = 'latest'

# Bun
bun = 'latest'

# Deno
deno = 'latest'

# Golang
go = 'latest'

# Node.js
node = ['lts', '23']

# Python
python = 'latest'

# Rust
rust = 'nightly'
'cargo:stylua' = 'latest'
